var list = {
    backStage: {
        '绩效分管理详情页': 'KPI_detail.html',
        '学生学币收支': 'student-coin-incoming.html',
        '机构管理': 'org-management.html',
        '机构管理-查看详情': 'org-seeDetail.html',
        '课程管理-教材管理': 'class-management.html',
        '课程管理-教材管理-创建教材': 'class-management-creatBook.html',
        '课程管理-教材管理-添加单词': 'class-management-addWords.html',
        '课程管理-教材管理-添加单元': 'class-management-addUnit.html',
        '课程管理-套课管理': 'class-management-aset.html',
        '课程管理-套课管理-套课详情': 'class-management-asetDetail.html',
        '课程管理-套课管理-添加套课': 'class-management-addAset.html',
        '课程管理-子课管理': 'class-management-childMange.html',
        '课程管理-子课管理-添加子课': 'class-management-addChildClass.html',
        '渠道管理': 'channel-management.html',
        '3.1人员管理': 'paper-manage.html',
        '3.2人员信息': 'person-mesg.html',
        '3.3 编辑人员信息': 'edit-personMesg.html',
        '4.10  修改密码': 'editPassword.html',
        '3.2人员信息管理': 'person-manage.html',
        '4.1学生管理': 'student-manage.html',
        '4.2 学生详情': 'student-detail.html',
        "4.3编辑学生信息": 'edit-student-mesg.html',
        '4.4班级管理': 'class-manage.html',
        '4.5报告列表': 'report-list.html',
        '4.6报告详情': 'report-detail.html',
        '4.7 课程管理': 'curriculum-manage.html',
        "4.8 绩效分管理": "Performance-score.html",
        "4.9 学生学币收支": "student-coins.html",
        "单元满分榜": 'unit-fullMarks.html',
        "课程进度统计": 'lesson-statistics.html',
        "课堂精彩瞬间": "lesson-wonderfulMoent.html",
        "学习量统计": 'learning-statistics.html',
        "运营分析-合同期限": "analysis-period.html",
        "运营分析-老师开通分析": 'analysis-teacher.html',
        "运营分析-学生开通分析": "analysis-cross.html",
        "运营分析-学生学情分析": 'analysis-student-situation.html',
        "统计-储值记录": 'resive-anysis.html'
    }

};